-- Creación de la BBDD de Eventos Relevantes para el tratamiento de las bolsas BMW y BIVA

CREATE TABLE P_BOLSAS_EVENTOS_RELEVANTES (
    FECHA      DATE,
    N          NUMBER ,
    CLAVE      VARCHAR2(15),
    SECCION    VARCHAR2(80),
    ASUNTO     VARCHAR2(500),
    URL        VARCHAR2(350),
    ARCHIVO    VARCHAR2(250),
    ORIGEN     VARCHAR2(6),
    T          VARCHAR2(2),
    FILTRO     VARCHAR2(10),
    FPROCESO   DATE
);


CREATE UNIQUE INDEX idx_P_BOLSAS_EVENTOS_RELEVANTES
ON P_BOLSAS_EVENTOS_RELEVANTES(FECHA, N, CLAVE, SECCION, ASUNTO, URL, ARCHIVO, ORIGEN, T, FILTRO);